name = "svg-renderer"
main = "src/index.ts"
compatibility_date = "2025-11-01"


[[rules]]
globs = ["**/*.ttf"]
type = "Data"


[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true